/* ame-next — BUILD-TIME shader baker (render.txt).
 *
 * Host tool: reads the GLSL module files under shaders/ and emits plain
 * C string literals (generated/shaders_gen.c/.h) that the C23 engine
 * links directly. The shaders live as SEPARATE FILES in the repo (the
 * source of truth); the baked table is what ships (identical on native
 * and web, no runtime file IO, no asset paths in tests).
 *
 * usage: bake_shaders <out_prefix> <name=path> [<name=path> ...]
 *   name is the lookup key the engine uses (e.g. lit.vert); #include
 *   resolution matches the include's basename against these names.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int emit_escaped(FILE *out, const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "bake_shaders: cannot open %s\n", path);
        return -1;
    }
    fputc('"', out);
    int c;
    while ((c = fgetc(f)) != EOF) {
        if (c == '\n') {
            fputs("\\n\"\n\"", out); /* one literal per source line */
        } else if (c == '"' || c == '\\') {
            fputc('\\', out);
            fputc(c, out);
        } else if (c >= 32 && c < 127) {
            fputc(c, out);
        } else if (c == '\t') {
            fputs("\\t", out);
        } else {
            fprintf(out, "\\x%02x", c);
        }
    }
    fputs("\"\n", out);
    fclose(f);
    return 0;
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "usage: %s <out_prefix> <name=path> ...\n", argv[0]);
        return 1;
    }
    const char *prefix = argv[1];

    char path_c[512], path_h[512];
    snprintf(path_c, sizeof path_c, "%s.c", prefix);
    snprintf(path_h, sizeof path_h, "%s.h", prefix);
    /* the .c includes its own header by the prefix's basename */
    const char *base = strrchr(prefix, '/');
    base = base ? base + 1 : prefix;

    FILE *out_c = fopen(path_c, "w");
    FILE *out_h = fopen(path_h, "w");
    if (!out_c || !out_h) {
        fprintf(stderr, "bake_shaders: cannot write %s.*\n", prefix);
        return 1;
    }

    fprintf(out_h, "/* GENERATED by tools/bake_shaders.c — do not edit. */\n");
    fprintf(out_h, "#ifndef AME_SHADERS_GEN_H\n#define AME_SHADERS_GEN_H\n");
    fprintf(out_h, "typedef struct { const char *name; const char *src; } ame_shader_src;\n");
    fprintf(out_h, "extern const ame_shader_src ame_shaders[];\n");
    fprintf(out_h, "extern const int ame_shader_count;\n");
    fprintf(out_h, "#endif\n");

    fprintf(out_c, "/* GENERATED by tools/bake_shaders.c — do not edit. */\n");
    fprintf(out_c, "#include \"%s.h\"\n", base);
    for (int i = 2; i < argc; i++) {
        char *eq = strchr(argv[i], '=');
        if (!eq || eq == argv[i] || !eq[1]) {
            fprintf(stderr, "bake_shaders: bad entry '%s' (want name=path)\n",
                    argv[i]);
            fclose(out_c);
            fclose(out_h);
            return 1;
        }
        *eq = '\0';
        /* C identifier from the loop index (names need no sanitizing) */
        fprintf(out_c, "static const char ame_shader_src_%d[] =\n", i - 2);
        if (emit_escaped(out_c, eq + 1) != 0) {
            fclose(out_c);
            fclose(out_h);
            return 1;
        }
        fprintf(out_c, ";\n");
    }
    fprintf(out_c, "const ame_shader_src ame_shaders[] = {\n");
    for (int i = 2; i < argc; i++) {
        /* argv[i] already holds just the name (split in the loop above) */
        fprintf(out_c, "    { \"%s\", ame_shader_src_%d },\n", argv[i], i - 2);
    }
    fprintf(out_c, "};\nconst int ame_shader_count = %d;\n", argc - 2);
    fclose(out_c);
    fclose(out_h);
    printf("baked %d shaders -> %s.c/h\n", argc - 2, prefix);
    return 0;
}
