/* ame-next — BUILD-TIME font baker (text.txt decision 4/5).
 *
 * Host tool: reads a .ttf, rasterizes the glyph ranges into ONE atlas, and
 * emits plain C arrays (generated/font_atlas.c/.h) that the C23 engine links
 * directly. Deterministic, zero startup cost, identical on native and web.
 *
 * The baker is a host tool: it is never linked into the engine, and it is the
 * single TU that touches stb_truetype (external/, warning-exempt).
 *
 * usage: bake_font <font.ttf> <pixel_size> <out_prefix>
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STB_TRUETYPE_IMPLEMENTATION /* single TU, build-time tool only */
#include <stb_truetype.h>           /* external/stb include dir */

/* glyph ranges: latin, latin-1 supplement + latin-ext-A, cyrillic */
static const struct { uint32_t lo, hi; } RANGES[] = {
    { 0x20, 0x7E },   /* basic latin */
    { 0xA0, 0xFF },   /* latin-1 supplement */
    { 0x100, 0x17F }, /* latin extended-A */
    { 0x400, 0x4FF }, /* cyrillic + cyrillic supplement */
};

#define ATLAS_W_DEFAULT 1024
#define ATLAS_H_DEFAULT 1024

int main(int argc, char **argv) {
    if (argc < 4) {
        fprintf(stderr, "usage: %s <font.ttf> <pixel_size> <out_prefix> "
                "[sym_prefix] [mac_prefix] [metric_div] [atlas_w] "
                "[atlas_h]\n", argv[0]);
        return 1;
    }
    const char *ttf_path = argv[1];
    int px = atoi(argv[2]);
    const char *prefix = argv[3];
    /* optional renames: defaults reproduce the historical font_atlas.* */
    const char *sym = argc > 4 ? argv[4] : "ame_font";
    const char *mac = argc > 5 ? argv[5] : "AME_FONT";
    double mdiv = argc > 6 ? atof(argv[6]) : 1.0;
    int atlas_w = argc > 7 ? atoi(argv[7]) : ATLAS_W_DEFAULT;
    int atlas_h = argc > 8 ? atoi(argv[8]) : ATLAS_H_DEFAULT;
    if (!(mdiv > 0.0))
        mdiv = 1.0;
    if (atlas_w < 64)
        atlas_w = ATLAS_W_DEFAULT;
    if (atlas_h < 64)
        atlas_h = ATLAS_H_DEFAULT;

    FILE *f = fopen(ttf_path, "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", ttf_path); return 1; }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    unsigned char *data = malloc((size_t)len);
    if (fread(data, 1, (size_t)len, f) != (size_t)len) { fprintf(stderr, "read fail\n"); return 1; }
    fclose(f);

    stbtt_fontinfo info;
    if (!stbtt_InitFont(&info, data, 0)) { fprintf(stderr, "stbtt_InitFont failed\n"); return 1; }
    float scale = stbtt_ScaleForPixelHeight(&info, (float)px);

    int ascent, descent, line_gap;
    stbtt_GetFontVMetrics(&info, &ascent, &descent, &line_gap);
    float ascent_px = ascent * scale;
    float descent_px = -descent * scale; /* positive distance below baseline */
    float line_h = ascent_px + descent_px + line_gap * scale + px * 0.25f;

    /* shelf packer state */
    unsigned char *atlas = calloc((size_t)atlas_w * atlas_h, 1); /* coverage A8 */
    int cx = 1, cy = 1, row_h = 0;

    char path_c[512], path_h[512];
    snprintf(path_c, sizeof path_c, "%s.c", prefix);
    snprintf(path_h, sizeof path_h, "%s.h", prefix);
    FILE *out_c = fopen(path_c, "w");
    FILE *out_h = fopen(path_h, "w");
    if (!out_c || !out_h) { fprintf(stderr, "cannot write %s/\n", prefix); return 1; }

    /* the .c includes its own header by the prefix's basename */
    const char *base = strrchr(prefix, '/');
    base = base ? base + 1 : prefix;

    fprintf(out_h, "/* GENERATED by tools/bake_font.c — do not edit. */\n");
    fprintf(out_h, "#ifndef %s_ATLAS_H\n#define %s_ATLAS_H\n", mac, mac);
    fprintf(out_h, "#include <stdint.h>\n");
    fprintf(out_h, "typedef struct {\n    uint32_t cp;\n    uint16_t ax, ay, aw, ah; /* atlas rect */\n");
    fprintf(out_h, "    int16_t xoff, yoff;    /* px, relative to pen (baseline) */\n");
    fprintf(out_h, "    float advance;         /* px per codepoint */\n");
    fprintf(out_h, "} %s_glyph;\n", sym);
    fprintf(out_h, "#define %s_ATLAS_WIDTH %d\n#define %s_ATLAS_HEIGHT %d\n", mac, atlas_w, mac, atlas_h);
    fprintf(out_h, "#define %s_PX %d\n", mac, px);
    fprintf(out_h, "#define %s_ASCENT %.2ff\n", mac, ascent_px / mdiv);
    fprintf(out_h, "#define %s_DESCENT %.2ff\n", mac, descent_px / mdiv);
    fprintf(out_h, "#define %s_LINE_H %.2ff\n", mac, line_h / mdiv);
    if (mdiv != 1.0) {
        /* divided metrics: cells are px, layout is px/mdiv (the quad
         * size factor; UVs still span full-res cells) */
        fprintf(out_h, "#define %s_LAYOUT_PX %.2ff\n", mac, px / mdiv);
    }
    fprintf(out_h, "extern const unsigned char %s_atlas_a8[%d];\n", sym, atlas_w * atlas_h);
    fprintf(out_h, "extern const %s_glyph %s_glyphs[];\n", sym, sym);
    fprintf(out_h, "extern const int %s_glyph_count;\n", sym);
    fprintf(out_h, "#endif\n");

    fprintf(out_c, "/* GENERATED by tools/bake_font.c — do not edit. */\n");
    fprintf(out_c, "#include \"%s.h\"\n", base);
    fprintf(out_c, "const %s_glyph %s_glyphs[] = {\n", sym, sym);

    int written = 0;
    for (size_t r = 0; r < sizeof RANGES / sizeof RANGES[0]; r++) {
        for (uint32_t cp = RANGES[r].lo; cp <= RANGES[r].hi; cp++) {
            int gw, gh, xoff, yoff;
            unsigned char *bmp = stbtt_GetCodepointBitmap(&info, 0, scale, (int)cp,
                                                          &gw, &gh, &xoff, &yoff);
            int advance, lsb;
            stbtt_GetCodepointHMetrics(&info, (int)cp, &advance, &lsb);
            if (gw == 0 || gh == 0 || !bmp) {
                /* space & friends: metrics only, no atlas cell */
                stbtt_FreeBitmap(bmp, NULL);
                if (cp == ' ') {
                    fprintf(out_c, "    { 0x%X, 0,0,0,0, 0,0, %.2ff },\n",
                            cp, advance * scale / mdiv);
                    written++;
                }
                continue;
            }
            /* padding 1px against bleed (render.txt rule 3 wants >= 1-2px;
               we pad by starting cells at 1 and leaving 1px stride gaps) */
            if (cx + gw + 1 > atlas_w) {
                cx = 1;
                cy += row_h + 1;
                row_h = 0;
            }
            if (cy + gh + 1 > atlas_h) {
                fprintf(stderr, "atlas full at U+%04X\n", cp);
                stbtt_FreeBitmap(bmp, NULL);
                free(atlas);
                free(data);
                return 1;
            }
            for (int yy = 0; yy < gh; yy++)
                memcpy(atlas + (size_t)(cy + yy) * atlas_w + (size_t)cx,
                       bmp + (size_t)yy * (size_t)gw, (size_t)gw);
            stbtt_FreeBitmap(bmp, NULL); /* audit fix: was leaked per glyph */
            if (gh > row_h) row_h = gh;
            /* bearings round to int16 layout px (round-half-away); the
             * advance stays float-exact: it drives the snapped pen. */
            fprintf(out_c, "    { 0x%X, %d,%d,%d,%d, %d,%d, %.2ff },\n",
                    cp, cx, cy, gw, gh,
                    (int)llround(xoff / mdiv), (int)llround(yoff / mdiv),
                    advance * scale / mdiv);
            written++;
            cx += gw + 1;
        }
    }
    fprintf(out_c, "};\nconst int %s_glyph_count = %d;\n", sym, written);

    /* atlas bytes emitted AFTER the (complete) glyph table */
    fprintf(out_c, "const unsigned char %s_atlas_a8[%d] = {\n", sym, atlas_w * atlas_h);
    for (int i = 0; i < atlas_w * atlas_h; i++) {
        if (i % 32 == 0) fprintf(out_c, "\n");
        fprintf(out_c, "%d,", atlas[i]);
    }
    fprintf(out_c, "\n};\n");

    fclose(out_c);
    fclose(out_h);
    /* audit fix (P0): this tool runs at BUILD time - a leak here fails
     * the whole ASan build under LSan (ninja exit 1). Free everything. */
    free(atlas);
    free(data);
    printf("baked %d glyphs at %dpx -> %s.c/h (line_h=%.1f ascent=%.1f)\n",
           written, px, prefix, line_h / mdiv, ascent_px / mdiv);
    return 0;
}
