#!/usr/bin/env python3
"""Jam-style YAML → C lines table. Reads dialogues/*.yaml, writes embedded_dialogues_gen.c."""
import pathlib, re, sys

def parse(path: pathlib.Path):
    lines = []
    speaker = "GLITCHER"
    for raw in path.read_text().splitlines():
        s = raw.strip()
        if s.startswith("speaker:"):
            speaker = s.split(":", 1)[1].strip()
        elif s.startswith("text:"):
            text = s.split(":", 1)[1].strip()
            lines.append(f"{speaker}: {text}")
    return lines

def main():
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    dlg = root / "dialogues"
    out = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else root / "examples/biscuit/embedded_dialogues_gen.c")
    all_lines = []
    for y in sorted(dlg.glob("*.yaml")):
        all_lines.extend(parse(y))
    body = ",\n".join(f'    "{ln}"' for ln in all_lines) or '    ""'
    out.write_text(
        "/* generated by tools/dialogue_yaml_to_c.py — do not edit */\n"
        f"const char *const BF_DIALOGUE_LINES[] = {{\n{body}\n}};\n"
        f"const int BF_DIALOGUE_N_LINES = {len(all_lines)};\n"
    )
    print("wrote", out, "n=", len(all_lines))

if __name__ == "__main__":
    main()
