// Auto-generated by tools/dialogue_yaml_to_c.py
// Do not edit by hand.
#include "ame_dialogue.h"
#include <stddef.h>

static const AmeDialogueOption sample_opts_1[] = {
    {"Yes, please", "explain"},
    {"No, thanks", "end"},
};

static const AmeDialogueLine sample_lines[] = {
    { "start", "Guide", "Welcome to A Mongoose Engine!", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Guide", "Would you like to hear about controls?", NULL, NULL, NULL, NULL, NULL, NULL, NULL, sample_opts_1, 2 },
    { "explain", "Guide", "Use mouse to draw in the line_draw example.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { "end", "Guide", "Okay, have fun!", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
};

static const AmeDialogueScene scene_sample = { .scene="sample", .lines=sample_lines, .line_count=sizeof(sample_lines)/sizeof(sample_lines[0]) };

const AmeDialogueScene *ame__generated_scenes[] = {
    &scene_sample,
};

const size_t ame__generated_scenes_count = sizeof(ame__generated_scenes)/sizeof(ame__generated_scenes[0]);
